### ISSUE TITLE
Day 6 without map

### ISSUE THREAD

**Issue by kpym** [lynerist/Advent-of-code-2022-golang#1]
I like very much your solutions, but in the yestaerday's one, I think you could avoid allocating and using a map.
The idea is to use a sliding window of all different characters. 
And to chek if the next character is already in the window. Then stop when the window is large enought.

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	//Read input file
	input, _ := os.ReadFile("input.txt")

	const differentCharactersNeeded = 4
	j := 0 
	for i := 1; i < len(input); i++ {
		for k := j; k < i; k++ {
			if input[k] == input[i] {
				j = k + 1
				break
			}
		}
		if i-j+1 == differentCharactersNeeded {
			fmt.Println(i + 1)
			break
		}
	}
}
```

Thi is not an issue, but as you have not activated the discussions for this repo, I write it here.

**Comment by lynerist** [comment]
Yes but a map costs just O(1) when you have to check the presence of the character in the window.

I use it like a set, I think that keeping a sliding window and growing it just with new characters would be way harder to implement than using a set. That's because adding an element in a set is an idempotent operation so I don't have to check if it's already there.
